export const MOCK_CATEGORIES = [
  {
    id: "1",
    name: "Electronics",
    image: "/api/placeholder/64/64",
    productCount: 1250,
    slug: "electronics",
  },
  {
    id: "2",
    name: "Fashion",
    image: "/api/placeholder/64/64",
    productCount: 2100,
    slug: "fashion",
  },
  {
    id: "3",
    name: "Home & Garden",
    image: "/api/placeholder/64/64",
    productCount: 890,
    slug: "home-garden",
  },
  {
    id: "4",
    name: "Sports",
    image: "/api/placeholder/64/64",
    productCount: 650,
    slug: "sports",
  },
  {
    id: "5",
    name: "Books",
    image: "/api/placeholder/64/64",
    productCount: 3200,
    slug: "books",
  },
  {
    id: "6",
    name: "Toys",
    image: "/api/placeholder/64/64",
    productCount: 720,
    slug: "toys",
  },
  {
    id: "7",
    name: "Beauty",
    image: "/api/placeholder/64/64",
    productCount: 980,
    slug: "beauty",
  },
  {
    id: "8",
    name: "Automotive",
    image: "/api/placeholder/64/64",
    productCount: 450,
    slug: "automotive",
  },
];

export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones with Noise Cancellation",
    price: 89.99,
    originalPrice: 129.99,
    image: "/api/placeholder/300/300",
    rating: 4.5,
    reviewCount: 128,
    seller: "TechStore",
    inStock: true,
  },
  {
    id: "2",
    name: "Smart Fitness Tracker with Heart Rate Monitor",
    price: 149.99,
    image: "/api/placeholder/300/300",
    rating: 4.2,
    reviewCount: 89,
    seller: "FitGear",
    inStock: true,
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt - Premium Quality",
    price: 24.99,
    originalPrice: 34.99,
    image: "/api/placeholder/300/300",
    rating: 4.7,
    reviewCount: 256,
    seller: "EcoFashion",
    inStock: true,
  },
  {
    id: "4",
    name: "Professional Camera Lens 50mm f/1.8",
    price: 299.99,
    image: "/api/placeholder/300/300",
    rating: 4.8,
    reviewCount: 67,
    seller: "PhotoPro",
    inStock: false,
  },
  {
    id: "5",
    name: "Ergonomic Office Chair with Lumbar Support",
    price: 199.99,
    originalPrice: 249.99,
    image: "/api/placeholder/300/300",
    rating: 4.4,
    reviewCount: 143,
    seller: "OfficeComfort",
    inStock: true,
  },
  {
    id: "6",
    name: "Smart Home Security Camera System",
    price: 179.99,
    image: "/api/placeholder/300/300",
    rating: 4.3,
    reviewCount: 94,
    seller: "SecureHome",
    inStock: true,
  },
  {
    id: "7",
    name: "Premium Kitchen Knife Set with Wooden Block",
    price: 79.99,
    originalPrice: 99.99,
    image: "/api/placeholder/300/300",
    rating: 4.6,
    reviewCount: 187,
    seller: "ChefTools",
    inStock: true,
  },
  {
    id: "8",
    name: "Wireless Charging Pad for Smartphones",
    price: 29.99,
    image: "/api/placeholder/300/300",
    rating: 4.1,
    reviewCount: 312,
    seller: "TechStore",
    inStock: true,
  },
];
